#!/bin/sh   
#
#ver20230907
#CAMBIAR CONTRASINAL ADMINPC
clear;
echo "Cambio de contrasinal para o usuario adminpc...";
sudo passwd adminpc;
clear;
echo "Confirmación do novo contrasinal...";
sudo echo "Contrasinal novo confirmado";
#CAMBIAR CONTRASINAL USUARIO PROFESOR
clear;
echo "Cambio de contrasinal para o usuario profesor...";
sudo passwd profesor;
clear;
echo "Confirmación do novo contrasinal...";
sudo echo "Contrasinal novo confirmado";

#COMPROBANDO SE XA SE PUXO CONTRASINAL AO GRUB
if [ -f /home/adminpc/grubpassword ];
	then 
		echo "O grub xa ten contrasinal";
	else
		clear;
		sudo ls;
		clear;
		echo "Vaise asignar un contrasinal para evitar a modificación ao grub";
		echo "A continuación teclea unha vez o contrasinal e preme enter";
		echo "E a continuación volve teclear o mesmo contrasinal e a preme enter";
		sudo grub-mkpasswd-pbkdf2 > grubtemp;
		sed -i '1,2d' grubtemp;
		sed -i 's/^O hash de PBKDF2 do seu contrasinal é //g' grubtemp;
		vargrub=`cat grubtemp`;
		sudo cp -f /etc/grub.d/00_header /opt/.00_header.backup;
		sudo cp -f /etc/grub.d/10_linux /opt/.10_linux.backup;
		sudo cp -f /etc/grub.d/30_os-prober /opt/.30_os-prober.backup;
		sudo sed -i '$a\cat << EOF' /etc/grub.d/00_header;
		sudo sed -i '$a\set superusers="adminpc"' /etc/grub.d/00_header;
		sudo sed -i '$a\password_pbkdf2 adminpc passgrub' /etc/grub.d/00_header;
		sudo sed -i "s/passgrub/$vargrub/" /etc/grub.d/00_header;
		sudo sed -i '$a\EOF' /etc/grub.d/00_header;
		sudo update-grub;
		sudo sed -i '/$menuentry_id_option/s/${CLASS}/${CLASS} --unrestricted/g' /etc/grub.d/10_linux;
		sudo update-grub;
		sudo sed -i '/osprober-chain-$(grub_get_device_id/s/ {/ --unrestricted {/g' /etc/grub.d/30_os-prober;
		sudo update-grub;
		sudo update-grub2;
		sudo rm -f grubtemp;
		sudo touch /home/adminpc/grubpassword;
fi

#PERSONALIZACIÓN USUARIO ALUMNO
if id -nG alumno | grep -qw nopasswdlogin;
	then
		echo "Login alumno sen contrasinal";
	else
		sudo gpasswd -a alumno nopasswdlogin;
fi

mozo_alumno=`egrep -c 'mozoblacklist' /etc/group`;
	case $mozo_alumno in
		0) sudo addgroup mozoblacklist;
		   sudo chmod 705 /usr/bin/mozo;
		   sudo chgrp mozoblacklist /usr/bin/mozo;
		   sudo adduser alumno mozoblacklist;;
		*) echo "Usuario alumno en mozoblacklist";;
	esac

#AMOSAR MENÚ DO GRUB AO INICIO
if [ `egrep -c 'hidden' /etc/default/grub` = '1' ] || [ `egrep -c '5' /etc/default/grub` = '0' ];
	then
		sudo sed -i 's/GRUB_TIMEOUT_STYLE="hidden"/GRUB_TIMEOUT_STYLE=""/g' /etc/default/grub;
		sudo sed -i 's/GRUB_TIMEOUT="0"/GRUB_TIMEOUT="5"/g' /etc/default/grub;
		sudo update-grub;
		sudo update-grub2;
fi

#COMPROBAR QUE O ESCRITORIO DO USUARIO ALUMNO ESTÁ BLOQUEADO
owner=`stat -c "%U" /home/alumno/Escritorio`;
if [ $owner = 'alumno' ];
	then
    	sudo chown adminpc /home/alumno/Escritorio;
		sudo chmod 755 -R /home/alumno/Escritorio;
fi

#DESCARGAR EXTRA_INTRANET
sudo rm -f extra_intrane*;
wget http://$rede/scripts/extra_intranet;
sed -i '/tempo_espera/d' extra_intranet; #eliminar a espera de 10'
sudo sh extra_intranet;

#REINICIAR O SERVIZO DE AUTOACTUALIZACIÓNS
sudo systemctl start updates-cronjob.service;

#COMPROBAR IDIOMAS
sudo /usr/bin/gnome-language-selector;

#COMPROBAR HARDWARE
#sudo /usr/bin/software-properties-gtk --open-tab=4;

#DESACTIVAR SERVIZO AO INICIO
#clear;
#echo "DESACTIVA O SPEECH-DISPATCHER";
#gksu bum;

#BORRAR ESTE SCRIPT
#sudo rm -f /home/alumno/extra;
#sudo rm -f /home/profesor/extra;

#COMPROBACIÓN DO TIPO DE DISCO QUE TEN O PC E SE É SSD COMPROBAR QUE TEN AHCI ACTIVO
sudo blkid > /tmp/particions;
sudo lspci > $HOME/ahci;
if [ `egrep -c 'mmcblk0p1' /tmp/particions` = '1' ] || [ `cat /sys/block/sda/queue/rotational` = '0' ];
	then
		if [ `egrep -c 'AHCI' $HOME/ahci` = '0' ];
		    then
		        clear;
		        echo "ATENCIÓN:";
		        echo "O disco duro é SSD pero non ten activado o modo AHCI na Bios";
		        echo "Preme unha tecla para continuar";
		        read avisoahci
		        case $avisoahci in
		            *) clear;;
	            esac
	            rm -f $HOME/ahci;
            else
                echo "Disco duro SSD co modo AHCI activo";
   	            rm -f $HOME/ahci;
        fi
fi

#REINICIAR SESIÓN GRÁFICA DE PROFESOR
clear;
echo "A que usuario hai que resetearlle os paneis?";
echo "a) alumno";
echo "p) profesor";
read reseteo_paneis;
case $reseteo_paneis in
a) su - alumno -c /usr/bin/layout-personalizado-ubuntu-mate;;
p) su - profesor -c /usr/bin/layout-personalizado-ubuntu-mate;;
A) su - alumno -c /usr/bin/layout-personalizado-ubuntu-mate;;
P) su - profesor -c /usr/bin/layout-personalizado-ubuntu-mate;;
*) ;;
esac
